# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tailor.Item'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
