# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0005_auto_20191210_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
