# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(default='img/avator.png', upload_to='images/'),
        ),
    ]
