# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0004_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=50),
        ),
    ]
